Update Dockerfile
The openjdk image is deprecated and throws errors when I try to build. Check https://hub.docker.com/_/openjdk 

```sh
user@ubuntu:~/Desktop/poc-graphql$ sudo docker build -t poc-graphql .
[+] Building 1.5s (3/3) FINISHED                                                                        docker:default
 => [internal] load build definition from Dockerfile                                                              0.0s
 => => transferring dockerfile: 304B                                                                              0.0s
 => WARN: StageNameCasing: Stage name 'MAVEN_BUILD' should be lowercase (line 1)                                  0.0s
 => ERROR [internal] load metadata for docker.io/library/openjdk:8-jre-alpine                                     1.4s
 => CANCELED [internal] load metadata for docker.io/library/maven:3.5.2-jdk-8-alpine                              1.4s
------
 > [internal] load metadata for docker.io/library/openjdk:8-jre-alpine:
------

 1 warning found (use docker --debug to expand):
 - StageNameCasing: Stage name 'MAVEN_BUILD' should be lowercase (line 1)
Dockerfile:6
--------------------
   4 |     WORKDIR /build/
   5 |     RUN mvn package
   6 | >>> FROM openjdk:8-jre-alpine
   7 |     WORKDIR /app
   8 |     COPY --from=MAVEN_BUILD /build/target/graphql-poc.jar /app/
--------------------
ERROR: failed to build: failed to solve: openjdk:8-jre-alpine: failed to resolve source metadata for docker.io/library/openjdk:8-jre-alpine: docker.io/library/openjdk:8-jre-alpine: not found
```

Replaced with corretto, the official replacement for that image.